# 注意最好用驼峰命名法
project:
  isDebug: true
  filePath: E:/test

user:
  tokenLifeDays: 7
server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  redis:
    host: 192.168.20.10
    port: 6379
    database: 0
    password:
  mail:
    host:
    username:
    password:
    protocol: smtps
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 腾讯云COS配置
qcloud:
  cos:
    secretId:
    secretKey:
    region:
    url:
    bucketName:

# minio对象存储配置
minio:
  url:
  accessKey:
  secretKey:
  bucketName:

# 阿里云OSS配置
aliyun:
  oss:
    accessKeyId:
    accessKeySecret:
    endPoint:
    bucketName:
    urlPrefix:

#微信小程序
wx:
  app-id:
  app-secret:
  is-debug: true
